// DO NOT EDIT — generated by Supabase CLI
// Run: supabase gen types typescript --local > types/supabase.ts
// This file will be populated in Story 1.2 after schema migrations are applied.
export type Database = Record<string, never>
